# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - RentalAPI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
# firstly backend
  build-dotnet:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o "${{env.DOTNET_ROOT}}/RentalApi"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: "${{env.DOTNET_ROOT}}/RentalApi"

  migrate-database:
    runs-on: ubuntu-latest
    needs: build-dotnet
    steps:    
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.x'

      - name: Install Entity Framework Core Tools
        run: dotnet tool install --global dotnet-ef

      - name: Drop Vehilces
        env:
          ConnectionStrings__DefaultConnection: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
        run: dotnet ef database drop --project wypozyczalnia.Server --context VehiclesContext --force

      - name: Run EF Core Migrations Vehicles
        env:
          ConnectionStrings__DefaultConnection: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
        run: dotnet ef database update --project wypozyczalnia.Server --connection ${{ secrets.AZURE_SQL_CONNECTION_STRING }} --context VehiclesContext

      - name: Run EF Core Migrations Identity
        env:
          ConnectionStrings__DefaultConnection: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
        run: dotnet ef database update --project wypozyczalnia.Server --connection ${{ secrets.AZURE_SQL_CONNECTION_STRING }} --context ApplicationDbContext



  deploy:
    runs-on: ubuntu-latest
    needs: [build-dotnet, migrate-database]
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'RentalAPI'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_5B474C9AB33A4438966CC1BBC14FCE67 }}

          
